#  http://localhost:8080/oauth/authorize?client_id=clientapp&response_type=code&scope=read_user_info
server:
  port: 9000

  servlet:
    session:
      cookie:
        name: server-cookie
#security:
#  oauth2:
#    authorization:
#      token-key-access:
#    client:
#      authorized-grant-types:
