server:
  port: 9001
  servlet:
    session:
      cookie:
        name: oauth-client
oauth2-server-url: http://localhost:9000

security:
  oauth2:
    client:
      client-id: clientapp
      client-secret: 1234
      user-authorization-uri: ${oauth2-server-url}/oauth/authorize
      access-token-uri: ${oauth2-server-url}/oauth/token
    resource:
      jwt:
        key-uri: ${oauth2-server-url}/oauth/token_key
